include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for ttyd - Terminal Emulator
LUCI_DEPENDS:=+ttyd
LUCI_PKGARCH:=all
LUCI_CATEGORIES:=System

PKG_NAME:=luci-app-ttyd
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
